apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "john.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
  name: {{ include "john.etcdName" . }}
spec:
  ports:
    - name: client
      port: {{ .Values.etcd.port }}
      targetPort: client
    - name: peer
      port: {{ .Values.etcd.peerPort }}
      targetPort: peer
  selector:
    {{- include "john.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
