apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "john.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
  name: {{ include "john.etcdName" . }}
spec:
  replicas: {{ int .Values.etcd.replicas }}
  selector:
    matchLabels:
      {{- include "john.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: etcd
  template:
    metadata:
      labels:
        {{- include "john.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: etcd
    spec:
      containers:
        - command:
            - /usr/local/bin/etcd
          args:
            - --name=etcd
            - --data-dir=/etcd-data
            - {{ printf "--listen-client-urls=%s" .Values.etcd.listenClientURLs | quote }}
            - {{ printf "--advertise-client-urls=%s" (include "john.etcdAdvertiseClientURLs" .) | quote }}
            - {{ printf "--listen-peer-urls=%s" .Values.etcd.listenPeerURLs | quote }}
            - {{ printf "--initial-advertise-peer-urls=%s" (include "john.etcdInitialAdvertisePeerURLs" .) | quote }}
            - {{ printf "--initial-cluster=%s" (include "john.etcdInitialCluster" .) | quote }}
            - --initial-cluster-state=new
            - --log-level=info
            - --logger=zap
            - --log-outputs=stderr
          image: "{{ .Values.etcd.imageName }}"
          imagePullPolicy: {{ .Values.etcd.imagePullPolicy }}
          name: etcd
          ports:
            - name: client
              containerPort: {{ int .Values.etcd.port }}
            - name: peer
              containerPort: {{ int .Values.etcd.peerPort }}
          resources:
            requests:
              memory: {{ .Values.etcd.requests.memory | quote }}
              cpu: {{ .Values.etcd.requests.cpu | quote }}
            limits:
              memory: {{ .Values.etcd.limits.memory | quote }}
              cpu: {{ .Values.etcd.limits.cpu | quote }}
          volumeMounts:
            - mountPath: /etcd-data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
