name: multi-john
description: A Helm Chart for multi-john.
version: 0.1.9
appVersion: "0.1.9"
apiVersion: v1
keywords:
  - multi-john
sources:
  - https://github.com/adamanteye/multi-john
  - https://github.com/openwall/john
home: https://github.com/adamanteye/multi-john
